select * from t1
where [movie name] is not 'The Godfather (1972)'
and [movie name] is not 'The Dark Knight (2008)'
and [movie name] is not 'The Green Mile (1999)'
and [movie name] is not 'The Shawshank Redemption (1994)'
and [movie name] is not 'Intouchables (2011)'
and [movie name] is not 'The Lord of the Rings The Return of the King (2003)'
and [movie name] is not 'Schindlers List (1993)'
and [movie name] is not 'The Godfather Part II (1974)'
and [movie name] is not 'Gladiator (2000)'
and [movie name] is not 'Inception (2010)'
and [movie name] is not 'Pulp Fiction (1994)'
and [movie name] is not 'Wadjda (2012)'
and [movie name] is not 'Forrest Gump (1994)'
and [movie name] is not 'One Flew Over the Cuckoos Nest (1975)'
and [movie name] is not 'L�on (1994)'
and [movie name] is not '12 Angry Men (1957)'
and [movie name] is not 'Goodfellas (1990)'
and [movie name] is not 'American X (1998)'
and [movie name] is not 'Django Unchained (2012)'
and [movie name] is not 'Saving Private Ryan (1998)'
and [movie name] is not 'The Silence of the Lambs (1991)'
and [movie name] is not 'Rush (2013)Biography'
;